Try to fix formatting

diff --git a/scripts/hooks/pre-commit b/scripts/hooks/pre-commit
--- a/scripts/hooks/pre-commit
+++ b/scripts/hooks/pre-commit
@@ -10,7 +10,7 @@ STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.(cpp
 process_file() {
     FILE=$1
     echo "Processing $FILE"
-    /usr/local/opt/llvm/bin/clang-tidy "$FILE" --warnings-as-errors=* -fix -fix-errors -- -std=c++20
+    /usr/local/opt/llvm/bin/clang-tidy "$FILE" --warnings-as-errors=* -fix -fix-errors -- -std=c++20 | tee clang-tidy.log
     TIDY_STATUS=$?
     clang-format -i "$FILE"
     FORMAT_STATUS=$?
@@ -20,6 +20,13 @@ process_file() {
         echo "Exiting process_file due to clang-tidy or clang-format failure."
         exit 255
     fi
+
+    if grep -q "error:" clang-tidy.log; then
+        echo "clang-tidy found errors."
+        rm -f clang-tidy.log
+        exit 1
+    fi
+    
     echo "Both clang-tidy and clang-format passed for $FILE"
 }
 
